apiVersion: v1
kind: ResourceQuota
metadata:
  name: boutique-dev-quota
  namespace: boutique-dev
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "30"
    services: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: boutique-dev-limits
  namespace: boutique-dev
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "128Mi"
      defaultRequest:
        cpu: "100m"
        memory: "64Mi"
      max:
        cpu: "1"
        memory: "1Gi"
      min:
        cpu: "50m"
        memory: "32Mi"
