apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cartservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cart-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: productcatalogservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emailservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: checkoutservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice-sa
  namespace: boutique
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice-sa
  namespace: boutique
automountServiceAccountToken: false
