# Prod runs higher replica counts for availability and rolling update headroom
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: boutique-prod
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: boutique-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: boutique-prod
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  namespace: boutique-prod
spec:
  replicas: 2
